"""
Created on 16.11.2022

@author: wf
"""
# Justpy global configuration variables (deprecated as of 0.11)
# importing justpy_config does not set the variables if Compatbility.version is set
CRASH = None
COOKIE_MAX_AGE = None
CRASH = None
DEBUG = None
FAVICON = None
FRONTEND_ENGINE_TYPE = None
FRONTEND_ENGINE_LIBS = None
HOST = None
LATENCY = None
LOGGING_LEVEL = None
MEMORY_DEBUG = None
NO_INTERNET = None
PORT = None
SECRET_KEY = None
SESSION_COOKIE_NAME = "session"
SESSIONS = None
SSL_CERTFILE = None
SSL_KEYFILE = None
SSL_VERSION = None
STATIC_DIRECTORY = None
STATIC_NAME = None
STATIC_ROUTE = None
TAILWIND = None
UVICORN_LOGGING_LEVEL = None
VERBOSE = None
BASE_URL = None
USE_COOKIE_MIDDLEWARE = False
USE_SVELTE_SKELETON = True
SQLALCHEMY_DB_CONNECTION_URL = None
SQLALCHEMY_BASENAME = None
SQLALCHEMY_DBMODELS_PYMODULE_NAME  = None
AUTH_USER_MODEL = None
# Webpage caching
CACHE_WEBPAGES=True
NOSESSION_WEBPAGE_CACHESIZE = 10
SESSION_WEBPAGE_CACHESIZE = 10
